Granquet/config account sort
meli/meli pull request #12
Opened 2022-08-03 12:35 UTC by granquet

2022-08-03 12:44 UTC, granquet commented on src/conf.rs
> +use std::str::FromStr;
oops, this is unused, this is leftover from the previous version.

2022-08-19 08:12 UTC, epilys requested changes

2022-08-19 08:12 UTC, epilys commented on src/components/mail/listing.rs
> +use melib::conf::AccountSettings;
```suggestion
```

2022-08-19 08:12 UTC, epilys commented on src/conf.rs
> +                    let file = theme.unwrap().path();
```suggestion
                    let file = theme?.path();
```

2022-08-19 08:14 UTC, epilys commented
Looks good to me other than those really minor details! Ready to merge when these are fixed.

2022-08-25 09:51 UTC, epilys approved these changes

2022-08-25 09:52 UTC, merged